op/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, op_edit, op_getlist


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', op_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', op_edit, name='edit'),

    url(r'^api/op_getlist$', op_getlist, name='op_getlist'),
]

si/apps/ordacq/urls.py
# coding=utf-8
from django.conf.urls import url
from si.apps.ordacq.views import ordacq_create, ordacq_list, ordacq_update, ordacq_delete
from si.apps.ordacq.views import ordacq_export, ordacq_import
__author__ = 'Sig'


urlpatterns = [
    url(r'^$', ordacq_list, name='index'),
    url(r'^create/$', ordacq_create, name='create'),
    url(r'^export/$', ordacq_export, name='export'),
    url(r'^import/$', ordacq_import, name='import'),
    url(r'^(?P<pk>\d+)/update/$', ordacq_update, name='update'),
    url(r'^(?P<pk>\d+)/delete/$', ordacq_delete, name='delete'),
]

si/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .views import index, logout_view
from django.contrib.auth.views import login, password_change


urlpatterns = [
    url(r'^si/$', index, name="index"),
    url(r'^si/ordacq/', include('si.apps.ordacq.urls', namespace='ordacq', app_name='ordacq')),
    
    # Qui ci sono le parti vecchie
    url(r'^si/login/$', login, name='login'),
    url(r'^si/logout/$', logout_view, name='logout'),
    url(r'^si/passchange/$', password_change, {'post_change_redirect': '/si/'}),
    url(r'^admin/', include(admin.site.urls)),
 
] + static(settings.SIFILEDATA_URL, document_root=settings.SIFILEDATA_ROOT)
# url(r'^si/segnalazioni/', include('segnalazioni.urls', namespace="segnalazioni", app_name="segnalazioni")),

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


"""
   url(r'^si/iniziative/', include('iniziative.urls', namespace="iniziative", app_name="iniziative")),
    url(r'^si/fs/', include('sifilesmanager.urls', namespace="fs", app_name="fs")),
    url(r'^si/corsi/', include('corsi.urls', namespace="corsi", app_name="corsi")),
    
    url(r'^si/op/', include('op.urls', namespace="op", app_name="op")),
    url(r'^si/aziende/', include('aziende.urls', namespace="aziende", app_name="aziende"))
"""

si/apps/ordacq/models.py
# coding=utf-8
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.


class TabellaStatoOrdini(models.Model):
    """
    Definizione della tabella stato ordini che mi serve per la visione d'insieme.
    Questa tabella, in futuro potrebbe anche sparire in quanto sostituita da query su ordini e su altre
    tabelle.
    """
    # Qui definisco gli stati in modo che siano poi semplici da gestire.
    STATO_BOZZA = 1
    STATO_EMETTERE = 2
    STATO_FIRMATO = 3
    STATO_SPEDITO = 4
    STATO_CHOICES = (
        (STATO_BOZZA, 'Bozza'),
        (STATO_EMETTERE, 'Emettere'),
        (STATO_FIRMATO, 'Firmato'),
        (STATO_SPEDITO, 'Spedito')
    )

    TIPO_ACQ = 1
    TIPO_ABB = 2
    TIPO_CHOICES = (
        (TIPO_ACQ, 'Acquisto'),
        (TIPO_ABB, 'Abbonamento')
    )

    azienda = models.CharField(max_length=10, default="ASC")
    anno = models.CharField(max_length=10, default="2016/2017")
    # Il protocollo è il numero di protocollo dell'ordine, se presente. Posso avere più righe della tabella stato
    # ordini che fanno riferimento allo stesso ordine solo se in mesi differenti.
    protocollo = models.CharField(
        # Dovrebbe essere nella forma standard Camerana.
        max_length=6,
        validators=[MinLengthValidator(3)], verbose_name="Numero di protocollo dell'ordine se presente", blank=True)
    # Contratto è il riferimento al contratto, se esiste.
    contratto = models.CharField(
        max_length=80,
        verbose_name="Riferimento al contratto con il fornitore, se presente.", blank=True)
    data = models.DateField(
        verbose_name="Data dell'ordine")
    competenza = models.CharField(
        max_length=10,
        verbose_name="Mese di competenza dell'ordine, nel caso di più mesi devo inserire più righe")
    stato = models.IntegerField(choices=STATO_CHOICES, default=STATO_BOZZA)
    fornitore = models.CharField(
        max_length=80, verbose_name="Nome del fornitore")
    tipo = models.IntegerField(choices=TIPO_CHOICES, default=TIPO_ACQ)
    descrizione = models.CharField(max_length=120, verbose_name="Descrizione dell'ordine")
    iniziativa = models.CharField(max_length=80, verbose_name="Iniziativa/e di riferimento")
    imponibile = models.IntegerField(verbose_name="Imponibile dell'ordine")
    iva_presente = models.BooleanField(default=True, verbose_name="Mi dice se l'IVA è presente")
    iva_detraibile = models.IntegerField(verbose_name="Percentuale di IVA detraibile")
    totale_costo = models.IntegerField(verbose_name="Costo totale dell'ordine comprensivo di IVA indetraibile")
    pagamento = models.CharField(
        max_length=80,
        verbose_name="scadenza di pagamento dell'ordine")
    fatture_protocolli = models.CharField(
        max_length=80,
        verbose_name="Numero/i di protocollo delle fatture")
    note = models.CharField(
        max_length=1000,
        verbose_name="Eventuali note sull'ordine")

    in_uso = models.BooleanField(db_index=True, default=True, verbose_name="L'ordine è valido ?")

    # Date di creazione e di aggiornamento dell'elemento.
    data_aggiornamento = models.DateTimeField(auto_now=True)
    data_creazione = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fornitore + ' - ' + self.descrizione + ' - ' + self.protocollo

    def save(self, *args, **kwargs):
        if self.iva_presente:
            self.totale_costo = self.imponibile * 1.22 * (100 - self.iva_detraibile) / 100
        super(TabellaStatoOrdini, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Ordine"
        verbose_name_plural = "Ordini"

si/apps/ordacq/forms.py
# coding=utf-8
from django import forms
from .models import TabellaStatoOrdini


class TabellaStatoOrdiniForm(forms.ModelForm):
    class Meta:
        model = TabellaStatoOrdini
        fields = ('protocollo', 'contratto', 'data', 'competenza', 'stato', 'fornitore', 'tipo', 'descrizione',
                  'iniziativa', 'imponibile', 'iva_presente', 'iva_detraibile', 'pagamento',
                  'fatture_protocolli', 'note', 'in_uso')

si/apps/ordacq/views.py
# coding=utf-8
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponse
from .resources import OrdacqResource
from django.template.loader import render_to_string
from .models import TabellaStatoOrdini
from si.sig_decorators import has_permission
from si.apps.siprof.models import Profile
from .forms import TabellaStatoOrdiniForm
from tablib import Dataset

# Definisco qui il nome dell'applicazione come lo voglio nel Data Base in modo che sia uguale per tutte le viste.
THIS_APP = Profile.APP_ORDACQ


@has_permission(THIS_APP, Profile.OP_READ)
def ordacq_list(request):
    """
    Genera la vista con la lista della tabella stato ordini.
    ATTENZIONE che app deve contenere il nome dell'applicazione per la corretta gestione dei permessi quando vado
    a compilare il corpo delle tabelle.
    """
    ordacq = TabellaStatoOrdini.objects.all()
    return render(request, 'ordacq/ordacq_list.html', {'ordacq_list': ordacq, 'app': THIS_APP})


def partial_ordacq_list(request):
    """
    Riporta il dizionario con la lista degli ordini di acquisto per il rendering sul template.
    
    :param request: Oggetto 'request' della vista da cui parto.
    :return: Il dizionario completo da riportare via JsonResponse
    """
    data = dict()
    data['form_is_valid'] = True
    ordacq = TabellaStatoOrdini.objects.all()
    data['html_ordacq_list'] = render_to_string('ordacq/includes/partial_ordacq_list.html', {
        'ordacq_list': ordacq, 'app': THIS_APP}, request=request)
    return data


def save_ordacq_form(request, form, template_name):
    """
    Salva il form e rinfresca la tabella generale. Uso questa che è sostanzialmente comune alle due voci di Update
    e Create così da poter gestire correttamente i permessi.
    """
    data = dict()
    # Se ho dei dati da salvare e sono validi li salvo e ripreparo la lista degli items per il refresh.
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return JsonResponse(partial_ordacq_list(request))
        else:
            data['form_is_valid'] = False
    # Altrimenti propongo il form vuoto.
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@has_permission(THIS_APP, Profile.OP_ADD)
def ordacq_create(request):
    """
    Aggiungo un elemento alla lista degli ordini.
    """
    if request.method == 'POST':
        form = TabellaStatoOrdiniForm(request.POST)
    else:
        form = TabellaStatoOrdiniForm()
    return save_ordacq_form(request, form, 'ordacq/includes/partial_ordacq_create.html')


@has_permission(THIS_APP, Profile.OP_UPDATE)
def ordacq_update(request, pk):
    """
    Aggiorno un elemento della lista degli ordini.
    """
    book = get_object_or_404(TabellaStatoOrdini, pk=pk)
    if request.method == 'POST':
        form = TabellaStatoOrdiniForm(request.POST, instance=book)
    else:
        form = TabellaStatoOrdiniForm(instance=book)
    return save_ordacq_form(request, form, 'ordacq/includes/partial_ordacq_update.html')


@has_permission(THIS_APP, Profile.OP_DELETE)
def ordacq_delete(request, pk):
    """
    Cancello un item.
    La richiesta della conferma la trovo direttamente nel form.
    """
    ordacq = get_object_or_404(TabellaStatoOrdini, pk=pk)
    data = dict()
    if request.method == 'POST':
        ordacq.delete()
        return JsonResponse(partial_ordacq_list(request))
    else:
        context = {'ordacq': ordacq}
        data['html_form'] = render_to_string('ordacq/includes/partial_ordacq_delete.html',
                                             context, request=request)
    return JsonResponse(data)


@has_permission(THIS_APP, Profile.OP_EXPORT)
def ordacq_export(request):
    """
    Esporta la tabella in formato Excel.
    """
    ordacq_resource = OrdacqResource()
    dataset = ordacq_resource.export()
    response = HttpResponse(dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Aquisti.xls"'
    return response


@has_permission(THIS_APP, Profile.OP_IMPORT)
def ordacq_import(request):
    """
    Importa un file Excel con la lista degli Acquisti.
    """
    data = dict()
    if request.method == 'POST':
        ordacq_resource = OrdacqResource()
        dataset = Dataset()
        new_ordacq = request.FILES['myfile']

        imported_data = dataset.load(new_ordacq.read(), 'xls')
        result = ordacq_resource.import_data(dataset, dry_run=True)  # Test the data import
        if not result.has_errors():
            ordacq_resource.import_data(dataset, dry_run=False)  # Actually import now

        # return JsonResponse(partial_ordacq_list(request))
        return redirect('ordacq:index')
    else:
        context = dict()
        data['html_form'] = render_to_string('ordacq/includes/partial_ordacq_import.html',
                                             context, request=request)
    return JsonResponse(data)
    #return render(request, 'ordacq/includes/partial_ordacq_import.html', context)

templates/ordacq/includes/partial_ordacq_create.html
<form method="post" action="{% url 'ordacq:create' %}" class="js-ordacq-create-form">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Inserimento nuova voce Acquisto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% include 'ordacq/includes/partial_ordacq_form.html' %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Abbandona</button>
    <button type="submit" class="btn btn-primary btn-sm">Salva</button>
  </div>
</form>

templates/ordacq/includes/partial_ordacq_delete.html
<form method="post" action="{% url 'ordacq:delete' ordacq.id %}" class="js-ordacq-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">Elimina Acquisto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="lead">Sei sicuro di voler eliminare la voce di acquisto : <br>
      <strong>{{ ordacq.descrizione }}</strong>?
    </p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Abbandona</button>
    <button type="submit" class="btn btn-danger btn-sm">Elimina</button>
  </div>
</form>

templates/ordacq/includes/partial_ordacq_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.name }}</label>
    {% render_field field class="form-control-sm" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/ordacq/includes/partial_ordacq_import.html
  <!-- Import Data -->
  <form method="post" enctype="multipart/form-data" action="{% url 'ordacq:import' %}" class="js-ordacq-import-form">
    {% csrf_token %}

    <div class="modal-header">
      <h3 class="modal-title">Importa Acquisti</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

    <div class="modal-body form-group">
      <input type="file" name="myfile">
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Abbandona</button>
      <button type="submit" class="btn btn-primary btn-sm">Importa</button>
    </div>
  </form>

templates/ordacq/includes/partial_ordacq_list.html
{% for ordacq in ordacq_list %}
  <tr>
    <td>{{ ordacq.id }}</td>
    <td>{{ ordacq.protocollo }}</td>
    <td>{{ ordacq.data }}</td>
    <td>{{ ordacq.competenza }}</td>
    <td>{{ ordacq.stato }}</td>
    <td>{{ ordacq.fornitore }}</td>
    <td>{{ ordacq.descrizione }}</td>
    <td>
      {% if user|can_read:app %}
        <button type="button" class="btn btn-primary btn-sm js-update-ordacq"
          data-url="{% url 'ordacq:update' ordacq.id %}">
          <i class="fa fa-eye" aria-hidden="true"></i>
        </button>
      {% endif %}

      {% if user|can_update:app %}
        <button type="button" class="btn btn-primary btn-sm js-update-ordacq"
          data-url="{% url 'ordacq:update' ordacq.id %}">
          <i class="fa fa-pencil" aria-hidden="true"></i>
        </button>
      {% endif %}

      {% if user|can_delete:app %}
        <button type="button" class="btn btn-danger btn-sm js-delete-ordacq"
          data-url="{% url 'ordacq:delete' ordacq.id %}">
          <span class="fa fa-trash" aria-hidden="true"></span>
        </button>
      {% endif %}
    </td>
  </tr>
{% empty %}
    <tr>
      <td colspan="8" class="text-center bg-warning">Non sono presenti acquisti !</td>
    </tr>
{% endfor %}

templates/ordacq/includes/partial_ordacq_update.html
<form method="post" action="{% url 'ordacq:update' form.instance.pk %}" class="js-ordacq-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">Modifica Acquisto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {% include 'ordacq/includes/partial_ordacq_form.html' %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Abbandona</button>
    <button type="submit" class="btn btn-primary btn-sm">Salva</button>
  </div>
</form>