Documentazione/aziende/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, get_listanazioni, add_edit, get_listaziende
from .views import importanazioni, importaprovincie, importaaziende, importacontatti
__author__ = 'Sig'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', add_edit, name='edit'),
    # Sezione della API
    url(r'^api/get_listanazioni/$', get_listanazioni, name='get_listanazioni'),
    url(r'^api/2/$', get_listaziende),
    # Importazioni da Assocam
    url(r'^importa/nazioni/$', importanazioni, name='_i_nazioni'),
    url(r'^importa/provincie/$', importaprovincie, name='_i_provincie'),
    url(r'^importa/aziende/$', importaaziende, name='_i_aziende'),
    url(r'^importa/contatti/$', importacontatti, name='_i_contatti'),
]

aziende/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, get_listanazioni, add_edit, get_listaziende
from .views import importanazioni, importaprovincie, importaaziende, importacontatti
__author__ = 'Sig'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', add_edit, name='edit'),
    # Sezione della API
    url(r'^api/get_listanazioni/$', get_listanazioni, name='get_listanazioni'),
    url(r'^api/get_listaaziende/$', get_listaziende),
    # Importazioni da Assocam
    url(r'^importa/nazioni/$', importanazioni, name='_i_nazioni'),
    url(r'^importa/provincie/$', importaprovincie, name='_i_provincie'),
    url(r'^importa/aziende/$', importaaziende, name='_i_aziende'),
    url(r'^importa/contatti/$', importacontatti, name='_i_contatti'),
]

op/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, op_edit, op_getlist


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', op_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', op_edit, name='edit'),

    url(r'^api/op_getlist$', op_getlist, name='op_getlist'),
]

si/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .views import index, logout_view
from django.contrib.auth.views import login, password_change


urlpatterns = [
    url(r'^si/$', index, name="index"),
    url(r'^si/ordacq/', include('si.apps.ordacq.urls', namespace='ordacq', app_name='ordacq')),
    
    # Qui ci sono le parti vecchie
    url(r'^si/login/$', login, name='login'),
    url(r'^si/logout/$', logout_view, name='logout'),
    url(r'^si/passchange/$', password_change, {'post_change_redirect': '/si/'}),
    url(r'^admin/', include(admin.site.urls)),
 
] + static(settings.SIFILEDATA_URL, document_root=settings.SIFILEDATA_ROOT)
# url(r'^si/segnalazioni/', include('segnalazioni.urls', namespace="segnalazioni", app_name="segnalazioni")),

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


"""
   url(r'^si/iniziative/', include('iniziative.urls', namespace="iniziative", app_name="iniziative")),
    url(r'^si/fs/', include('sifilesmanager.urls', namespace="fs", app_name="fs")),
    url(r'^si/corsi/', include('corsi.urls', namespace="corsi", app_name="corsi")),
    
    url(r'^si/op/', include('op.urls', namespace="op", app_name="op")),
    url(r'^si/aziende/', include('aziende.urls', namespace="aziende", app_name="aziende"))
"""

Documentazione/aziende/models.py
# coding=utf-8
from mongoengine import *
from django.db import models
import datetime
from si.si    import concatena, hashsig
# from bson.objectid import ObjectId
"""
    Attenzione che per far funzionare il tutto bisogna creare un indice sparse su CF per evitare l'inserimento di
    valori duplicati nel codice fiscale (Per questo l'indice deve essere di tipo sparse...).
"""


# region Modello MongoDB
class Nazione(Document):
    """
    Collezione delle nazioni note.
    """
    nazione = StringField(max_length=80, required=True, primary_key=True)

    dts_aggiornamento = DateTimeField()
    dts_creazione = DateTimeField()

    def __str__(self):
        return self.nazione

    def save(self, *args, **kwargs):
        if not self.dts_creazione:
            self.dts_creazione = datetime.datetime.now()
        self.dts_aggiornamento = datetime.datetime.now()
        return super(Nazione, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Nazione"
        verbose_name_plural = "Nazioni"
        managed = False


class Provincia(Document):
    """
    Collezione delle Provincie (anche se non esistono più !)
    """
    sigla = StringField(max_length=2, required=True, primary_key=True)
    provincia = StringField(max_length=40)

    dts_aggiornamento = DateTimeField()
    dts_creazione = DateTimeField()

    def __str__(self):
        return concatena(self.provincia, " (", self.sigla, ")")

    def save(self, *args, **kwargs):
        if not self.dts_creazione:
            self.dts_creazione = datetime.datetime.now()
        self.dts_aggiornamento = datetime.datetime.now()
        return super(Provincia, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Provincia"
        verbose_name_plural = "Provincie"
        managed = False


class Azienda(Document):
    """
    Anagrafica Azienda
    """
    ragione_sociale = StringField(max_length=100, required=True)
    descrizione = StringField(max_length=200)
    # Vecchia chiave primaria di Assocam.
    id_asc_azienda = LongField()
    # TODO Devo essere sicuro che non possano essere inseriti due CF Uguali.
    cf = StringField(max_length=16, verbose_name="Codice Fiscale")
    mail_generica = EmailField()
    sito_web = StringField(max_length=50)
    note = StringField()
    hash = StringField(max_length=100)
    lista_sedi_html = StringField(max_length=1000)
    lista_contatti_html = StringField(max_length=2000)
    dts_aggiornamento = DateTimeField()
    dts_creazione = DateTimeField()
    # Definizione degli indici
    # Nello specifico indice testuale su hash.
    meta = {
        'indexes': ['$hash'],
        'collection': 'aziende_aziende'
    }

    def __str__(self):
        return self.ragione_sociale

    def save(self, *args, **kwargs):
        # Compone l'Hash dell'azienda.
        self.hash = hashsig(self.ragione_sociale)

        # Aggiorna i timestamps.
        if not self.dts_creazione:
            self.dts_creazione = datetime.datetime.now()
        self.dts_aggiornamento = datetime.datetime.now()
        return super(Azienda, self).save(*args, **kwargs)

    def aggiornacorrelazioni(self):
        """
        Aggiorna gli elementi delle correlazioni.
        """
        # Compone la lista delle sedi.
        sedi = Sede.objects(azienda=self)
        lista_sedi = ''
        for sede in sedi:
            if lista_sedi:
                lista_sedi += '<br>'
            lista_sedi += sede.indirizzo_verboso
        self.lista_sedi_html = lista_sedi

        # Compone la lista dei contatti.
        contatti = Contatto.objects(azienda=self)
        lista_contatti = ''
        for conta in contatti:
            if lista_contatti:
                lista_contatti += '<br>'
            lista_contatti += conta.contatto_verboso
        self.lista_contatti_html = lista_contatti

        # Infine salva l'istanza.
        self.save()

    class Meta:
        managed = False


class Sede(Document):
    """
    Sede di un'Azienda.
    """
    # _id = ObjectIdField(required=True, default=lambda: ObjectId())
    # Riferimento alla vecchia matricola Assocam
    id_asc_azienda = LongField()
    # Riferimento al record correlato dell'Azienda.
    azienda = ReferenceField(Azienda, reverse_delete_rule=DENY)
    # Campi specifici della singola sede.
    piva = StringField(max_length=12)
    indirizzo1 = StringField(max_length=50)
    indirizzo2 = StringField(max_length=50)
    comune = StringField(max_length=50)
    provincia = StringField(max_length=2)
    cap = StringField(max_length=5)
    nazione = StringField(max_length=50)
    indirizzo_verboso = StringField(max_length=200)
    tel1 = StringField(max_length=30)
    tel2 = StringField(max_length=30)
    tel3 = StringField(max_length=30)
    tel4 = StringField(max_length=30)
    doctel1 = StringField(max_length=20)
    doctel2 = StringField(max_length=20)
    doctel3 = StringField(max_length=20)
    doctel4 = StringField(max_length=20)
    sede_legale = BooleanField(default=False)
    attivo = BooleanField(default=True)
    promozione_ok = BooleanField(default=True)
    note = StringField()
    # contatti = EmbeddedDocumentListField(EmbeddedDocumentField(Contatto))
    dts_aggiornamento = DateTimeField()
    dts_creazione = DateTimeField()
    # Definizione degli indici.
    # Nello specifico su id_asc_azienda in quanto parte delle ricerche saranno fatte qui.
    meta = {
        'indexes': ['id_asc_azienda'],
        'collection': 'aziende_sedi'
    }

    def __str__(self):
        return self.indirizzo_verboso

    def save(self, *args, **kwargs):
        # Compone l'indirizzo verboso dell'azienda.
        dummy = concatena(self.indirizzo1, " ", self.indirizzo2, " - ", self.cap, " ", self.comune, " (",
                          self.provincia, ")")
        if self.nazione:
            dummy = concatena(dummy, " - ", self.nazione)
        self.indirizzo_verboso = dummy

        # Aggiorna i Timestamps.
        if not self.dts_creazione:
            self.dts_creazione = datetime.datetime.now()
        self.dts_aggiornamento = datetime.datetime.now()

        # Chiama il Super !
        return super(Sede, self).save(*args, **kwargs)

    class Meta:
        managed = False


class Contatto(Document):
    """
    Contatto all'interno di un'azienda.
    """
    # _id = ObjectIdField(required=True, default=lambda: ObjectId())
    # Riferimento alla vecchia matricola Assocam
    id_asc_azienda = LongField()
    id_asc_contatto = LongField()
    # Riferimento al record correlato dell'Azienda.
    azienda = ReferenceField(Azienda, reverse_delete_rule=DENY)
    sede = ReferenceField(Sede, reverse_delete_rule=DENY)
    # Campi specifici della singola sede.
    titolo = StringField(max_length=50)
    nome = StringField(max_length=50)
    cognome = StringField(max_length=50)
    posizione = StringField(max_length=50)
    contatto_verboso = StringField(max_length=200)
    tel1 = StringField(max_length=30)
    tel2 = StringField(max_length=30)
    tel3 = StringField(max_length=30)
    tel4 = StringField(max_length=30)
    doctel1 = StringField(max_length=20)
    doctel2 = StringField(max_length=20)
    doctel3 = StringField(max_length=20)
    doctel4 = StringField(max_length=20)
    email1 = EmailField()
    email2 = EmailField()
    data_nascita = DateTimeField()
    note = StringField()
    attivo = BooleanField(default=True)
    promozione_ok = BooleanField(default=True)
    hash = StringField(max_length=100)
    # Timestamp di creazione e di aggiornamento.
    dts_aggiornamento = DateTimeField()
    dts_creazione = DateTimeField()
    # Definizione degli indici.
    # Nello specifico su id_asc_azienda e su id_asc_contatto in quanto parte delle ricerche saranno fatte qui.
    meta = {
        'indexes': ['id_asc_azienda', 'id_asc_contatto'],
        'collection': 'aziende_contatti'
    }

    def __str__(self):
        return concatena(self.titolo, " ", self.cognome, " ", self.nome)

    def save(self, *args, **kwargs):
        # Calcola l'hash del contatto
        self.hash = hashsig(concatena(self.cognome, self.nome))

        # Compone il contatto verboso per il seguito.
        self.contatto_verboso = concatena(self.titolo, ' ', self.cognome, ' ', self.nome)

        # Aggiorna i Timestamps.
        if not self.dts_creazione:
            self.dts_creazione = datetime.datetime.now()
        self.dts_aggiornamento = datetime.datetime.now()

        # Chiama il super !
        return super(Contatto, self).save(*args, **kwargs)

    class Meta:
        managed = False
# endregion


# region API IMPORTAZIONE ASSOCAM
class NazioneSQL(models.Model):
    nazione = models.CharField(max_length=80, primary_key=True)

    class Meta:
        managed = False
        db_table = 'asc_nazioni'


class ProvinciaSQL(models.Model):
    sigla = models.CharField(max_length=2, primary_key=True)
    provincia = models.CharField(max_length=40)

    class Meta:
        managed = False
        db_table = 'asc_provincie'


class AziendaSQL(models.Model):
    id_azienda = models.IntegerField(primary_key=True, db_column='Id Azienda')
    ragione_sociale = models.CharField(max_length=100, db_column="Ragione Sociale")
    descrizione = models.CharField(max_length=200)
    indirizzo = models.CharField(max_length=50)
    citta = models.CharField(max_length=50)
    provincia = models.CharField(max_length=2)
    cap = models.CharField(max_length=5)
    piva = models.CharField(max_length=12)
    cf = models.CharField(max_length=16)
    tel1 = models.CharField(max_length=30)
    tel2 = models.CharField(max_length=30)
    tel3 = models.CharField(max_length=30)
    tel4 = models.CharField(max_length=30)
    dtel1 = models.CharField(max_length=20)
    dtel2 = models.CharField(max_length=20)
    dtel3 = models.CharField(max_length=20)
    dtel4 = models.CharField(max_length=20)
    sitoweb = models.CharField(max_length=50)
    note = models.CharField(max_length=5000)
    hashragionesociale = models.CharField(max_length=100)

Documentazione/aziende/forms.py
# coding=utf-8
from django.forms import TextInput
from .models import Nazione, Azienda
from mongodbforms import DocumentForm


class NazioneForm(DocumentForm):

    class Meta:
        model = Nazione

        fields = ['nazione']

        widgets = {
            'nazione': TextInput(attrs={'class': 'easyui-textbox', 'style': 'width:300px'}),
        }


class AziendaForm(DocumentForm):

    class Meta:
        model = Azienda

aziende/forms.py
# coding=utf-8
from django.forms import TextInput
from .models import Nazione, Azienda
from mongodbforms import DocumentForm


class NazioneForm(DocumentForm):

    class Meta:
        model = Nazione

        fields = ['nazione']

        widgets = {
            'nazione': TextInput(attrs={'class': 'easyui-textbox', 'style': 'width:300px'}),
        }


class AziendaForm(DocumentForm):

    class Meta:
        model = Azienda

templates/aziende/az_add_edit.html
{% extends "basejqx_old.html" %}

{% block title %}Aziende{% endblock %}

{%  block javascript %}
    <style type="text/css">
        ul.errorlist {
            margin: 0;
            padding: 0;
        }
        .errorlist li {
            background-color: red;
            color: white;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
        .fieldWrapper {
            margin: 10px;
        }
        .note {
            font-size: 15px;
            font-style: italic;
            margin: 10px;
        }
        .row {
            padding: 0 15px;
            margin: 15px -15px 15px;
        }
    </style>
    <script>
    $(document).ready(function () {
        // Creo i vari controlli.
        $("#id_ragione_sociale").jqxInput({width: 300, height: 25 });
        $("#id_cf").jqxInput({width: 200, height: 25 });
        $("#id_sito_web").jqxInput({width: 300, height: 25 });
        $("#id_note").jqxTextArea({ height: 90, width: 600, minLength: 1 });
        // Pulsanti
        $("#submitbutton").jqxButton({ template: "default" });
        $("#cancelbutton").jqxButton({ template: "danger" });
    });
    </script>

{% endblock %}

{% block body_block %}
<form id="ff" method="post">
    {% csrf_token %}

    <div class="row">
        <div class="col-md-7">
            {{ form.ragione_sociale.errors }}
            {{ form.ragione_sociale.label_tag }} {{ form.ragione_sociale }}
        </div>
        <div class="col-md-5">
            {{ form.cf.errors }}
            {{ form.cf.label_tag }} {{ form.cf }}
        </div>
    </div>
    <div class="row">
        {{ form.sito_web.errors }}
        {{ form.sito_web.label_tag }} {{ form.sito_web }}
    </div>
    <div class="row">
        {{ form.note.errors }}
        {{ form.note.label_tag }} {{ form.note }}
    </div>
    <div class="note">
        <br>
        Hash : {{ form.hash.value }} <br>
        Data Ultima Modifica : {{ form.dts_aggiornamento.value }} &nbsp;&nbsp;&nbsp;&nbsp;
        Data Creazione : {{ form.dts_creazione.value }}
    </div>
    <div align="center"><!-- Pulsanti -->
        <input style='margin-top: 20px;' type="submit" value="Salva" id='submitbutton' />
        <input style='margin-top: 20px;' type="cancel" value="Annulla" id='cancelbutton' />
    </div><!-- Pulsanti -->

</form>
{% endblock %}

templates/aziende/index.html
{% extends 'basejqx_old.html' %}
{% load staticfiles %}

{% block title %}Lista Aziende{% endblock %}

{% block javascript %}
 <script type="text/javascript">
        $(document).ready(function () {
            var filtro = $("#filtro");
            filtro.jqxButton();
            filtro.on("click", function () {

                $("#jqxgrid").jqxGrid('updatebounddata');
            });
            var url = "/si/aziende/api/get_listaaziende/";
            var grid = $("#jqxgrid");
            // prepare the data
            var source =
            {
                datatype: "json",
                datafields: [
                    { name: 'ragione_sociale' },
                    { name: 'sedi' },
                    { name: 'contatti' },
                    { name: 'pk' }
                ],
                id: 'pk',
                url: url,
                root: 'data',
                data: {
                    style: "full",
                    maxRows: 50
                }
            };
            var dataAdapter = new $.jqx.dataAdapter(source, {
                formatData: function (data) {
                    $.extend(data, {
                        filtroAzienda: $('#filtroAzienda').val(),
                        style: "full",
                        maxRows: 50
                    });
                return data;
            }
    });
            grid.jqxGrid({
                width: "100%",
                source: dataAdapter,
                columnsresize: true,
                editable: false,
                autoheight: true,
                autorowheight: true,
                pageable: true,
                pagesize: 20,
                filterable: true,
                sortable: true,
                autoshowfiltericon: true,
                columns: [
                    { text: 'Ragione Sociale', dataField: 'ragione_sociale', width: "40%" },
                    { text: 'Sedi', dataField: 'sedi', width: "30%" },
                    { text: 'Contatti', dataField: 'contatti', width: "30%" }
                ],
                showstatusbar: true,
                renderstatusbar: function (statusbar) {
                    // appends buttons to the status bar.
                    var container = $("<div style='overflow: hidden; position: relative; margin: 5px;'></div>");
                    var addButton = $("<div style='float: left; margin-left: 5px;'><img style='position: relative; margin-top: 2px;' src='../../images/add.png'/><span style='margin-left: 4px; position: relative; top: -3px;'>Add</span></div>");
                    var deleteButton = $("<div style='float: left; margin-left: 5px;'><img style='position: relative; margin-top: 2px;' src='../../images/close.png'/><span style='margin-left: 4px; position: relative; top: -3px;'>Delete</span></div>");
                    var reloadButton = $("<div style='float: left; margin-left: 5px;'><img style='position: relative; margin-top: 2px;' src='../../images/refresh.png'/><span style='margin-left: 4px; position: relative; top: -3px;'>Reload</span></div>");
                    var searchButton = $("<div style='float: left; margin-left: 5px;'><img style='position: relative; margin-top: 2px;' src='../../images/search.png'/><span style='margin-left: 4px; position: relative; top: -3px;'>Find</span></div>");
                    container.append(addButton);
                    container.append(deleteButton);
                    container.append(reloadButton);
                    container.append(searchButton);
                    statusbar.append(container);
                    addButton.jqxButton({  width: 60, height: 20 });
                    deleteButton.jqxButton({  width: 65, height: 20 });
                    reloadButton.jqxButton({  width: 65, height: 20 });
                    searchButton.jqxButton({  width: 50, height: 20 });
                    // add new row.
                    addButton.click(function (event) {
                        var datarow = generatedata(1);
                        $("#jqxgrid").jqxGrid('addrow', null, datarow[0]);
                    });
                    // delete selected row.
                    deleteButton.click(function (event) {
                        var selectedrowindex = $("#jqxgrid").jqxGrid('getselectedrowindex');
                        var rowscount = $("#jqxgrid").jqxGrid('getdatainformation').rowscount;
                        var id = $("#jqxgrid").jqxGrid('getrowid', selectedrowindex);
                        $("#jqxgrid").jqxGrid('deleterow', id);
                    });
                    // reload grid data.
                    reloadButton.click(function (event) {
                        $("#jqxgrid").jqxGrid({ source: getAdapter() });
                    });
                    // search for a record.
                    searchButton.click(function (event) {
                        var offset = $("#jqxgrid").offset();
                        $("#jqxwindow").jqxWindow('open');
                        $("#jqxwindow").jqxWindow('move', offset.left + 30, offset.top + 30);
                    });
                },
            });
            grid.on("celldoubleclick", function (event) {
                var args = event.args;
                var rowBoundIndex = args.rowindex;
                var colIndex = args.columnindex;
                var value = $('#jqxgrid').jqxGrid('getcellvalue', rowBoundIndex, 'pk');
                var url_mask = "{% url 'aziende:edit' pk=12345 %}".replace(/12345/, value.toString());
                alert (colIndex);
                popupCenter(url_mask, '80', '80');
            });
        });
    </script>
{% endblock %}


{% block body_block %}

<br>
<div>
    Filtro Ragione Sociale : <input type="text" id="filtroAzienda"/><input type="button" value="Go" id='filtro' /> <br><br>
</div>

<div id="jqxgrid"></div>

<div style="margin-left: 30px; float: left;">
    <div>
        <input id="addrowbutton" type="button" value="Add New Row" />
    </div>
    <div style="margin-top: 10px;">
        <input id="deleterowbutton" type="button" value="Delete Selected Row" />
    </div>
    <div style="margin-top: 10px;">
        <input id="updaterowbutton" type="button" value="Update Selected Row" />
    </div>
</div>


{% endblock %}