iniziative/urls.py
# coding=utf-8
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from iniziative.views import IniziativaAdd, IniziativaEdit, index, detail, sottoiniziativa_detail, \
    sottoiniziativa_add, sottoiniziativa_edit, gruppo_add, gruppo_edit, gruppo_detail, \
    iniziativa_delete, sottoiniziativa_delete, gruppo_delete, get_iniziative, get_sottoiniziative, \
    get_raggruppamenti
__author__ = 'Sig'


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', login_required(IniziativaAdd.as_view()), name='add'),
    url(r'^edit/(?P<pk>\d+)$', login_required(IniziativaEdit.as_view()), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', iniziativa_delete, name='delete'),
    url(r'^(?P<pk_iniziativa>\d+)/$', detail, name='detail'),

    url(r'^api/get_iniziative/$', get_iniziative, name='get_iniziative'),
    url(r'^api/get_sottoiniziative$', get_sottoiniziative, name='get_sottoiniziative'),
    url(r'^api/get_raggruppamenti$', get_raggruppamenti, name='get_raggruppamenti'),

    url(r'^(?P<pk_iniziativa>\d+)/subadd/$', sottoiniziativa_add, name='sub_add'),
    url(r'^subedit/(?P<pk>\d+)$', sottoiniziativa_edit, name='sub_edit'),
    url(r'^delete_sub/(?P<pk>\d+)$', sottoiniziativa_delete, name='sub_delete'),
    url(r'^sub/(?P<pk_sub>\d+)/$', sottoiniziativa_detail, name='sub_detail'),

    url(r'^(?P<pk_sub>\d+)/grpadd/$', gruppo_add, name='grp_add'),
    url(r'^grpedit/(?P<pk>\d+)$', gruppo_edit, name='grp_edit'),
    url(r'^delete_grp/(?P<pk>\d+)$', gruppo_delete, name='grp_delete'),
    url(r'^grp/(?P<pk_grp>\d+)/$', gruppo_detail, name='grp_detail'),
]

op/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, op_edit, op_getlist


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', op_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', op_edit, name='edit'),

    url(r'^api/op_getlist$', op_getlist, name='op_getlist'),
]

si/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .views import index, logout_view
from django.contrib.auth.views import login, password_change


urlpatterns = [
    url(r'^si/$', index, name="index"),
    url(r'^si/ordacq/', include('si.apps.ordacq.urls', namespace='ordacq', app_name='ordacq')),
    
    # Qui ci sono le parti vecchie
    url(r'^si/login/$', login, name='login'),
    url(r'^si/logout/$', logout_view, name='logout'),
    url(r'^si/passchange/$', password_change, {'post_change_redirect': '/si/'}),
    url(r'^admin/', include(admin.site.urls)),
 
] + static(settings.SIFILEDATA_URL, document_root=settings.SIFILEDATA_ROOT)
# url(r'^si/segnalazioni/', include('segnalazioni.urls', namespace="segnalazioni", app_name="segnalazioni")),

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


"""
   url(r'^si/iniziative/', include('iniziative.urls', namespace="iniziative", app_name="iniziative")),
    url(r'^si/fs/', include('sifilesmanager.urls', namespace="fs", app_name="fs")),
    url(r'^si/corsi/', include('corsi.urls', namespace="corsi", app_name="corsi")),
    
    url(r'^si/op/', include('op.urls', namespace="op", app_name="op")),
    url(r'^si/aziende/', include('aziende.urls', namespace="aziende", app_name="aziende"))
"""

iniziative/forms.py
# coding=utf-8
from django.forms import ModelForm, Textarea, TextInput, CharField, Form
from .models import Iniziativa, SottoIniziativa, Raggruppamento
from sigwidgets import JqxInput, JqxDataGrid
__author__ = 'Sig'


class ListaIniziativeForm(Form):
    """
    Form per la lista delle iniziative
    """
    your_name = CharField(widget=JqxDataGrid(jqwattrs={
            'width': '100%', 'url': '/si/iniziative/api/get_iniziative/',
            'columns': [
                {'text': 'Nome', 'dataField': 'nome', 'width': '20%'},
                {'text': 'Descrizione', 'dataField': 'descrizione', 'width': '80%'}
            ],
        }))


class IniziativaForm(ModelForm):
    """
    Form per l'aggiunta/modifica delle iniziative.
    """
    class Meta:
        model = Iniziativa
        fields = ['nome', 'descrizione']
        widgets = {
            'nome': JqxInput(jqwattrs={'width': 100, 'minLength': 5}),
            'descrizione': JqxInput(jqwattrs={'width': 400, 'minLength': 5})
        }
    

class SottoIniziativaForm(ModelForm):
    """
    Attenzione che il campo iniziativa che è una chiave esterna non lo metto proprio così il form potrà essere
    validato senza errori.
    Dopo la validazione scrivo la chiave esterna e poi lo salvo ma tutto questo lo farò nella view !
    """
    class Meta:
        model = SottoIniziativa
        fields = ['nome', 'descrizione', 'in_uso']
        widgets = {
            'nome': TextInput(attrs={'size': 60}),
            'descrizione': Textarea(attrs={'cols': 40, 'rows': 2}),
        }


class GruppoForm(ModelForm):
    """
    Attenzione che il campo sotto-iniziativa che è una chiave esterna non lo metto proprio così il form potrà essere
    validato senza errori.
    Dopo la validazione scrivo la chiave esterna e poi lo salvo ma tutto questo lo farò nella view !
    """
    class Meta:
        model = Raggruppamento
        fields = ['nome', 'descrizione', 'ordine', 'in_uso']
        widgets = {
            'nome': TextInput(attrs={'size': 60}),
            'descrizione': Textarea(attrs={'cols': 40, 'rows': 2}),
            'ordine': TextInput(attrs={'size': 60}),
        }

iniziative/views.py
# coding=utf-8
"""
 Ulcuni siti interessanti quanto a gestione del Fors.
 http://www.onespacemedia.com/news/2014/feb/5/getting-started-generic-class-based-views-django/
 http://tumivn.com/2014/09/16/develop-a-crud-movie-app-with-django-1-7/

 ORDINE GENEALE DELLE VISTE

 Index
 Add
 Edit
 Delete
 Detail
"""
import json

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView

from si.apps.siprof.models import Permissions
from si.sig_decorators import has_permission
from .forms import SottoIniziativaForm, GruppoForm, ListaIniziativeForm
from .models import Iniziativa, SottoIniziativa, Raggruppamento


# region INIZIATIVE
@has_permission(Permissions.APP_INIZIATIVE, Permissions.OP_READ)
def index(request):
    """
    INIZIATIVA : Indice generale ordinato per chiave primaria.
    """
    # Uso un form per gestire il controllo del gridview
    # lista_iniziative = Iniziativa.objects.filter(in_uso=True).order_by('pk')
    # context_dict = {'lista_iniziative': lista_iniziative, 'perm': perm}
    form = ListaIniziativeForm()

    # Popola il dizionario di interfaccia con la Griglia jqxGrid
    dj = {
        'url_add': reverse('corsi:add'),
        'url_del': reverse('corsi:del'),
        'url_edit': reverse('corsi:edit', kwargs={'pk': '12345'}),
        'url_detail': reverse('corsi:edit', kwargs={'pk': '12345'}),
        'sourcedata_url': '/si/corsi/api/get_corsi/',
        'sourcedata_max_row': 50,
        'sourcedata_data': """[
            {name: 'codice'},
            {name: 'denominazione'},
            {name: 'durata'},
            {name: 'ordine'},
            {name: 'pk'},
        ]""",
        'grid_columns': """[
            {text: 'Codice Corso', dataField: 'codice', width: "10%"},
            {text: 'Denominazione', dataField: 'denominazione', width: "70%"},
            {text: 'Durata', dataField: 'durata', width: "10%"},
            {text: 'Ordine', dataField: 'ordine', width: "10%"}
        ]"""
    }

    # Popola il dizionario per il template.
    context_dict = {'form': form, 'dj': dj}

    # Visualizza la risposta.
    return render(request, 'iniziative/index.html', context_dict)


class IniziativaAdd(CreateView):
    """
    INIZIATIVA : Creazione di una nuova iniziativa. !! Login required gestito in urls !!
    """
    model = Iniziativa
    template_name = 'iniziative/i_cu.html'
    success_url = '/si/iniziative/'
    fields = '__all__'


class IniziativaEdit(UpdateView):
    """
    INIZIATIVA : Modifica dei dati di un'iniziativa. !! Login required gestito in urls !!
    """
    template_name = 'iniziative/i_cu.html'
    model = Iniziativa
    success_url = '/si/iniziative/'
    fields = ['nome', 'descrizione', 'cup_cig', 'in_uso']


@login_required()
def iniziativa_delete(request, pk):
    """
    INIZIATIVA : Elimina l'iniziativa data se non ha figli.

    Non chiede conferma perchè la richiesta viene fatta a monte, prima di chiamare questa funzione.
    """
    # Cerca di recuperare l'iniziativa e se non ci riesce segnala errore.
    try:
        iniziativa = Iniziativa.objects.get(pk=pk)
    except Iniziativa.DoesNotExist:
        raise Http404("Indice iniziativa inesistente !")

    # Se l'iniziativa ha figli abbandona segnalando l'errore.
    if iniziativa.sottoiniziativa_set.count() > 0:
        context_dict = {'elemento': iniziativa,
                        'correlati': iniziativa.sottoiniziativa_set.all(),
                        'indietro': reverse('iniziative:index')}
        return render(request, 'e_delcorr.html', context_dict)

    # Altrimenti procede alla cancellazione.
    iniziativa.delete()
    return HttpResponseRedirect(reverse('iniziative:index'))


@login_required()
def detail(request, pk_iniziativa):
    """
    INIZIATIVA : Visualizzazione dei dettagli di un'iniziativa.
    """
    context_dict = {}

    try:
        # Recupero l'iniziativa da visualizzare.
        iniziativa = Iniziativa.objects.get(pk=pk_iniziativa)
        context_dict['iniziativa'] = iniziativa

        # Recupero tutte le sottoiniziative correlate.
        sottoiniziative = SottoIniziativa.objects.filter(iniziativa=pk_iniziativa)
        context_dict['sottoiniziative'] = sottoiniziative

    except Iniziativa.DoesNotExist:
        # Se l'Iniziativa non esiste arrivo qui in modo silente e con il dizionario vuoto per cui il template
        # visualizzerà : Nessuna iniziativa presente.
        pass

    # Visualizza il template.
    return render(request, 'iniziative/i_dtl.html', context_dict)
# endregion


# region SOTTO-INIZIATIVE
@login_required()
def sottoiniziativa_add(request, pk_iniziativa):
    """
    SOTTO-INIZIATIVA : Data un'iniziativa ci aggiunge una sotto iniziativa.
    """
    # Cerca di recuperare l'iniziativa e se non ci riesce segnala errore.
    try:
        iniziativa = Iniziativa.objects.get(pk=pk_iniziativa)
    except Iniziativa.DoesNotExist:
        raise Http404("Indice iniziativa inesistente !")

    # Legge i dati dal POST e li analizza per salvarli
    if request.method == 'POST':
        form = SottoIniziativaForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.iniziativa = iniziativa
            post.save()
            return HttpResponseRedirect(reverse('iniziative:detail', kwargs={'pk_iniziativa': pk_iniziativa}))
        else:
            print(form.errors)
    else:
        form = SottoIniziativaForm()

    # Popola il dizionario per il template.
    context_dict = {'form': form, 'iniziativa': iniziativa, 'blocktitle': 'Sotto Iniziativa', 'header':
                    'Sotto Iniziativa di ' + iniziativa.nome}

    # Visualizza il template.
    return render(request, 'si_cu_formasp_t1.html', context_dict)


@login_required()
def sottoiniziativa_edit(request, pk):
    """
    SOTTO-INIZIATIVA : Modifica dei dati della sotto iniziativa.
    """
    # Cerca di recuperare la sotto iniziativa e se non ci riesce segnala errore.
    try:
        sottoiniziativa = SottoIniziativa.objects.get(pk=pk)
    except SottoIniziativa.DoesNotExist:
        raise Http404("Indice sotto iniziativa inesistente !")

    # Legge i dati dal POST e li analizza per salvarli
    if request.method == 'POST':
        form = SottoIniziativaForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            sottoiniziativa.nome = post.nome
            sottoiniziativa.descrizione = post.descrizione
            sottoiniziativa.save()
            return HttpResponseRedirect(reverse('iniziative:detail',
                                                kwargs={'pk_iniziativa': sottoiniziativa.iniziativa.pk}))
        else:
            print(form.errors)
    else:
        form = SottoIniziativaForm(instance=sottoiniziativa)

    # Popola il dizionario per il template.
    context_dict = {'form': form, 'iniziativa': sottoiniziativa.iniziativa, 'blocktitle': 'Sotto Iniziativa', 'header':
                    'Sotto Iniziativa di : ' + sottoiniziativa.iniziativa.nome}

    # Visualizza il template.
    return render(request, 'si_cu_formasp_t1.html', context_dict)


@login_required()
def sottoiniziativa_delete(request, pk):
    """
    SOTTO-INIZIATIVA : Elimina la sotto iniziativa data se non ha figli.

    Non chiede conferma perchè la richiesta viene fatta a monte, prima di chiamare questa funzione.
    """
    # Cerca di recuperare l'iniziativa e se non ci riesce segnala errore.
    try:
        sottoiniziativa = SottoIniziativa.objects.get(pk=pk)
    except SottoIniziativa.DoesNotExist:
        raise Http404("Indice sotto-iniziativa inesistente !")

    # Se la sotto-iniziativa ha figli abbandona segnalando errore.
    if sottoiniziativa.raggruppamento_set.count() > 0:
        context_dict = {'elemento': sottoiniziativa,
                        'correlati': sottoiniziativa.raggruppamento_set.all(),
                        'indietro': reverse('iniziative:sub_detail', kwargs={'pk_sub': pk})}
        return render(request, 'e_delcorr.html', context_dict)

    # Altrimenti procede con la cancellazione e torna alla pagina di dettaglio dell'iniziativa padre.
    iniziativa = sottoiniziativa.iniziativa
    sottoiniziativa.delete()
    return HttpResponseRedirect(reverse('iniziative:detail', kwargs={'pk_iniziativa': iniziativa.pk}))


@login_required()
def sottoiniziativa_detail(request, pk_sub):
    """
    SOTTO-INIZIATIVA : Visualizzazione dei dettagli della sottoiniziativa.
    """
    context_dict = {}

    try:
        # Recupera la sottoiniziativa.
        sottoiniziativa = SottoIniziativa.objects.get(pk=pk_sub)
        context_dict['sottoiniziativa'] = sottoiniziativa

        # Recupera l'iniziativa padre.
        iniziativa = sottoiniziativa.iniziativa
        context_dict['iniziativa'] = iniziativa

        # Recupera la lista dei raggruppamenti
        raggruppamenti = Raggruppamento.objects.filter(sotto_iniziativa=pk_sub)
        context_dict['raggruppamenti'] = raggruppamenti

    except SottoIniziativa.DoesNotExist:
        # Se la sotto iniziativa non esiste non fa nulla in quanto il caso è già contemplato nel template.
        pass

    # Visualizza il template.
    return render(request, 'iniziative/sub_detail.html', context_dict)
# endregion


# region RAGGRUPPAMENTO
@login_required()
def gruppo_add(request, pk_sub):
    """
    GRUPPO : Data una sotto iniziativa ci aggiunge un gruppo.
    """
    # Cerca di recuperare la sotto iniziativa e se non ci riesce segnala errore.
    try:
        sottoiniziativa = SottoIniziativa.objects.get(pk=pk_sub)
    except SottoIniziativa.DoesNotExist:
        raise Http404("Indice sotto-iniziativa inesistente !")

    # Legge i dati dal POST e li analizza per salvarli
    if request.method == 'POST':
        form = GruppoForm(request.POST)

templates/iniziative/grp_detail.html
{% extends 'base-jqxrenamed.html' %}

{% block title %}Dettaglio Raggruppamento{% endblock %}
{% block header %}Dettaglio Raggruppamento{% endblock %}

{% block body_block %}

<table border="1" style="width:100%">
    <tr class="thead">
        <td>Raggruppamento : {{ gruppo.nome }}</td>
        <td>Sotto Iniziativa Padre : {{ sottoiniziativa.nome }}</td>
        <td>Iniziativa Radice : {{ iniziativa.nome }}</td>
    </tr>
    <tr>
        <td>
            Descrizione: {{ gruppo.descrizione }}<br>
            Ordine: {{ gruppo.ordine }}<br>
            In uso : {{ gruppo.in_uso|yesno:"Si,No" }}
        </td>
        <td>
            Descrizione: {{ sottoiniziativa.descrizione }}<br>
            In uso : {{ sottoiniziativa.in_uso|yesno:"Si,No" }}
        </td>
        <td>
            Descrizione: {{ iniziativa.descrizione }}<br>
            CUP/CIG: {{ iniziativa.cup_cig }}<br>
            In uso : {{ iniziativa.in_uso|yesno:"Si,No" }}
        </td>
    </tr>
    <tr class="small">
        <td>
            Data Aggiornamento: {{ gruppo.data_aggiornamento|date }}<br>
            Data Creazione: {{ gruppo.data_creazione|date }}
        </td>
        <td>
            Data Aggiornamento: {{ sottoiniziativa.data_aggiornamento|date }}<br>
            Data Creazione: {{ sottoiniziativa.data_creazione|date }}
        </td>
        <td>
            Data Aggiornamento: {{ iniziativa.data_aggiornamento|date }}<br>
            Data Creazione: {{ iniziativa.data_creazione|date }}
        </td>
    </tr>
</table>

<p class="text-center">
    <a href="javascript:void(0)" class="easyui-linkbutton" onclick="window.history.back();"
           data-options="iconCls:'icon-back'">Indietro
    </a>
    <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:grp_edit' gruppo.pk %}">Modifica</a>
</p>

{% endblock %}

templates/iniziative/i_cu.html
{% extends "base-jqxrenamed.html" %}

{% block title %}Iniziativa{% endblock %}
{% block header %}Iniziativa{% endblock %}

{% block body_block %}
<script>
    function submitForm(){
        document.getElementById("ff").submit();
    }

    function clearForm(){
        document.getElementById("ff").reset();
    }
</script>

<form id="ff" class="easyui-panel" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <div align="center">
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()" data-options="iconCls:'icon-save'">Salva</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="clearForm()" data-options="iconCls:'icon-clear'">Clear</a>
        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="window.location = '{% url 'iniziative:index' %}'"
           data-options="iconCls:'icon-back'">Indietro
        </a>
    </div>
</form>
{% endblock %}

templates/iniziative/i_dtl.html
{% extends 'base-jqxrenamed.html' %}

{% load si_templatetags %}

{% block title %}Dettaglio Iniziativa{% endblock %}
{% block header %}Dettaglio Iniziativa{% endblock %}

{% block body_block %}

{% si_dc_dialog %}


<p class="thead">Iniziativa: {{ iniziativa.nome }}</p>

<p>
    Descrizione: {{ iniziativa.descrizione }}<br>
    CUP/CIG: {{ iniziativa.cup_cig }}<br>
    In uso : {{ iniziativa.in_uso|yesno:"Si,No" }}
</p>

<p>
    <small>
        Data Aggiornamento: {{ iniziativa.data_aggiornamento|date:"DATE_FORMAT" }}<br>
        Data Creazione: {{ iniziativa.data_creazione|date:"DATE_FORMAT" }}
    </small>
</p>

<p class="text-center">
    <a class="easyui-linkbutton" iconCls="icon-back" href="{% url 'iniziative:index' %}">Indietro</a>
    <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:edit' iniziativa.pk %}">Modifica</a>
</p>


{% if sottoiniziative %}
    <table  class="easyui-datagrid" title="Sottoiniziative correlate">
        <thead>
            <tr>
                <th data-options="field:'Nome'">Nome</th>
                <th data-options="field:'Descrizione'">Descrizione</th>
                <th data-options="field:'Azione'">Azione</th>
            </tr>
        </thead>
        {% for sotto_iniziativa in sottoiniziative %}
            <tr>
                <td><a href="{% url 'iniziative:sub_detail' sotto_iniziativa.pk %}">{{ sotto_iniziativa.nome }}</a></td>
                <td>{{ sotto_iniziativa.descrizione }}</td>
                <td>
                    <a titolo="Cancellazione Sotto-Iniziativa" item="{{ sotto_iniziativa.nome }}"
                       link="{% url 'iniziative:sub_delete' sotto_iniziativa.pk %}"
                       class="easyui-linkbutton remove_link" data-options="iconCls:'icon-cancel'" href="{% url 'index' %}">Del
                    </a>
                    <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:sub_edit' sotto_iniziativa.pk %}">Edit</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <div class="si-title">Sottoiniziative correlate</div>
    <div class="jumbotron">
        Nessuna Presente !
    </div>
{% endif %}

<div align="center">
    <p>
        <a class="easyui-linkbutton" iconCls="icon-add" href="{% url 'iniziative:sub_add' iniziativa.pk %}">Aggiungi Sottoiniziativa</a>
    </p>
</div>

{% endblock %}

templates/iniziative/i_index.html
{% extends 'base-jqxrenamed.html' %}

{% load si_templatetags %}

{% block title %}Lista Iniziative{% endblock %}
{% block header %}Lista Iniziative{% endblock %}

{% block body_block %}

    {% si_dc_dialog %}

    {% if lista_iniziative %}
        <div>
            <table class="easyui-datagrid">
                <thead>
                    <tr>
                        <th data-options="field:'Nome'">Nome</th>
                        <th data-options="field:'Descrizione'">Descrizione</th>
                        <th data-options="field:'Azione'">Azione</th>
                    </tr>
                </thead>

                <tbody>
                {% for iniziativa in lista_iniziative %}
                    <tr>
                        <td><a href="{% url 'iniziative:detail' iniziativa.pk %}">{{ iniziativa.nome }}</a></td>
                        <td>{{ iniziativa.descrizione }}</td>
                        <td>
                            <a titolo="Cancellazione Iniziativa" item="{{ iniziativa.nome }}"
                               link="{% url 'iniziative:delete' iniziativa.pk %}"
                               class="easyui-linkbutton remove_link" iconCls="icon-cancel" href="{% url 'index' %}">
                            Del</a>
                            <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:edit' iniziativa.pk %}">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
       <div class="si-title">Iniziative</div>
        <div class="jumbotron">
            Nessuna Presente !
        </div>
    {% endif %}

    <div align="center">
        <p>
            <a class="easyui-linkbutton" iconCls="icon-add" href="{% url 'iniziative:add' %}">Aggiungi iniziativa</a>
        </p>
    </div>
{% endblock %}

templates/iniziative/sub_detail.html
{% extends 'base-jqxrenamed.html' %}

{% load si_templatetags %}

{% block title %}Dettaglio Sotto Iniziativa{% endblock %}
{% block header %}Dettaglio Sotto Iniziativa{% endblock %}

{% block body_block %}

{% si_dc_dialog %}

<table border="1" style="width:100%">
    <tr class="thead">
        <td>Sotto Iniziativa : {{ sottoiniziativa.nome }}</td>
        <td>Iniziativa Padre : {{ iniziativa.nome }}</td>
    </tr>
    <tr>
        <td>
            Descrizione: {{ sottoiniziativa.descrizione }}<br>
            In uso : {{ sottoiniziativa.in_uso|yesno:"Si,No" }}
        </td>
        <td>
            Descrizione: {{ iniziativa.descrizione }}<br>
            CUP/CIG: {{ iniziativa.cup_cig }}<br>
            In uso : {{ iniziativa.in_uso|yesno:"Si,No" }}
        </td>
    </tr>
    <tr class="small">
        <td>
            Data Aggiornamento: {{ sottoiniziativa.data_aggiornamento|date }}<br>
            Data Creazione: {{ sottoiniziativa.data_creazione|date }}
        </td>
        <td>
            Data Aggiornamento: {{ iniziativa.data_aggiornamento|date }}<br>
            Data Creazione: {{ iniziativa.data_creazione|date }}
        </td>
    </tr>
</table>

<p class="text-center">
    <a class="easyui-linkbutton" iconCls="icon-back" href="{% url 'iniziative:detail' iniziativa.pk %}">Indietro</a>
    <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:sub_edit' sottoiniziativa.pk %}">Modifica</a>
</p>

{% if raggruppamenti %}
    <table  class="easyui-datagrid" title="Raggruppamenti Correlati">
        <thead>
            <tr>
                <th data-options="field:'Nome'">Nome</th>
                <th data-options="field:'Descrizione'">Descrizione</th>
                <th data-options="field:'Azione'">Azione</th>
            </tr>
        </thead>
        {% for raggruppamento in raggruppamenti %}
            <tr>
                <td><a href="{% url 'iniziative:grp_detail' raggruppamento.pk %}">{{ raggruppamento.nome }}</a></td>
                <td>{{ raggruppamento.descrizione }}</td>
                <td>
                    <a titolo="Cancellazione Raggruppamento" item="{{ raggruppamento.nome }}"
                       link="{% url 'iniziative:grp_delete' raggruppamento.pk %}"
                       class="easyui-linkbutton remove_link" data-options="iconCls:'icon-cancel'" href="{% url 'index' %}">Del
                    </a>

                    <a class="easyui-linkbutton" iconCls="icon-edit" href="{% url 'iniziative:grp_edit' raggruppamento.pk %}">Edit</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <div class="si-title">Raggruppamenti Correlati</div>
    <div class="jumbotron">
        Nessuno Presente !
    </div>
{% endif %}

<div align="center">
    <p>
        <a class="easyui-linkbutton" iconCls="icon-add" href="{% url 'iniziative:grp_add' sottoiniziativa.pk %}">Aggiungi Raggruppamento</a>
    </p>
</div>

{% endblock %}