op/urls.py
# coding=utf-8
from django.conf.urls import url
from .views import index, op_edit, op_getlist


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', op_edit, name='add'),
    url(r'^edit/(?P<pk>\w+)$', op_edit, name='edit'),

    url(r'^api/op_getlist$', op_getlist, name='op_getlist'),
]

si/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from .views import index, logout_view
from django.contrib.auth.views import login, password_change


urlpatterns = [
    url(r'^si/$', index, name="index"),
    url(r'^si/ordacq/', include('si.apps.ordacq.urls', namespace='ordacq', app_name='ordacq')),
    
    # Qui ci sono le parti vecchie
    url(r'^si/login/$', login, name='login'),
    url(r'^si/logout/$', logout_view, name='logout'),
    url(r'^si/passchange/$', password_change, {'post_change_redirect': '/si/'}),
    url(r'^admin/', include(admin.site.urls)),
 
] + static(settings.SIFILEDATA_URL, document_root=settings.SIFILEDATA_ROOT)
# url(r'^si/segnalazioni/', include('segnalazioni.urls', namespace="segnalazioni", app_name="segnalazioni")),

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


"""
   url(r'^si/iniziative/', include('iniziative.urls', namespace="iniziative", app_name="iniziative")),
    url(r'^si/fs/', include('sifilesmanager.urls', namespace="fs", app_name="fs")),
    url(r'^si/corsi/', include('corsi.urls', namespace="corsi", app_name="corsi")),
    
    url(r'^si/op/', include('op.urls', namespace="op", app_name="op")),
    url(r'^si/aziende/', include('aziende.urls', namespace="aziende", app_name="aziende"))
"""

sifilesmanager/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from sifilesmanager.views import index, fileupload, folder_add, folder_edit, folder_delete, file_delete
__author__ = 'Sig'


urlpatterns = [
    url(r'^(?P<pk>\d+|None)$', index, name='index'),
    url(r'^$', index, name='index'),
    url(r'^up/$', fileupload, name='upload'),
    url(r'^up/(?P<pk>\d+)$', fileupload, name='upload'),
    url(r'^folderadd/(?P<inodenumber>\d+|None)$', folder_add, name='folder_add'),
    url(r'^folderedit/(?P<pk>\d+)$', folder_edit, name='folder_edit'),
    url(r'^folderdelete/(?P<pk>\d+)$', folder_delete, name='folder_delete'),
    url(r'^filedelete/(?P<pk>\d+)$', file_delete, name='file_delete'),
]

sifilesmanager/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import hashlib
import os


fs = FileSystemStorage(location=settings.SIFILEDATA_ROOT)


def upload_to_sha1(instance, filename):
    full_path = os.path.normcase(os.path.normpath(instance.pathurl))
    dest = os.path.join(full_path, instance.url)
    print(dest)
    return dest


class INode(models.Model):
    """
    I Node.
    Sono i nomi delle Cartelle in cui organizzo i files.
    """
    nome = models.CharField(max_length=80)
    descrizione = models.TextField(max_length=200)
    padre = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, default=None)
    data_aggiornamento = models.DateTimeField(auto_now=True)
    data_creazione = models.DateTimeField(auto_now_add=True)


class SiFile(models.Model):
    """
    Modello dei files memorizzati con chiave sha1 per memorizzazione efficiente.
    """
    nome = models.CharField(max_length=80)
    descrizione = models.TextField(max_length=200)
    sha1_hash = models.CharField(db_index=True, max_length=40, unique=True)  # TODO non deve essere NULL
    pathurl = models.CharField(max_length=2)
    url = models.CharField(max_length=38)
    filename = models.FileField(upload_to=upload_to_sha1, storage=fs)  # TODO che faccio con le collisioni ?
    inode = models.ForeignKey(INode, on_delete=models.PROTECT, null=True, blank=False, default=None)
    size = models.PositiveIntegerField(default=0)
    data_aggiornamento = models.DateTimeField(auto_now=True)
    data_creazione = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Salva il nome del file in nome.
        self.nome = self.filename
        self.size = self.filename.size

        # Salva l'hash sha1 del file in sha1_hash
        h = hashlib.sha1()
        for chunk in self.filename.chunks():
            h.update(chunk)
        sha1 = h.hexdigest()
        self.sha1_hash = sha1

        # Compone i campi di urlpath e di url per la memorizzazione del file.
        self.url = sha1[2:]
        self.pathurl = sha1[:2]

        super(SiFile, self).save(*args, **kwargs)

sifilesmanager/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Sig'
from django.forms import ModelForm
from .models import SiFile, INode


class SiFileForm(ModelForm):
    """
    Qui mostro sono il nome e la descrizione per la finestra di popup.
    """
    class Meta:
        model = SiFile
        fields = ['filename', 'descrizione']


class INodeForm(ModelForm):
    """
    Attenzione che il campo 'padre' che è una chiave esterna non lo metto proprio così il form potrà essere
    validato senza errori.
    Dopo la validazione scrivo la chiave esterna e poi lo salvo ma tutto questo lo farò nella view !
    """
    class Meta:
        model = INode
        fields = ['nome', 'descrizione']

sifilesmanager/views.py
# -*- coding: utf-8 -*-
# Create your views here.
from .forms import SiFileForm, INodeForm
from .models import SiFile
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import INode
from django.conf import settings
import os


# region FILES
def inodeslista(nodopadre=None):
    """
    Dato un nodo padre mi da la lista delle cartelle e dei files contenuti al suo interno.
    """
    lista_inodes = INode.objects.filter(padre=nodopadre).order_by('nome')
    lista_files = SiFile.objects.filter(inode=nodopadre).order_by('nome')

    dizionario = {'lista_inodes': lista_inodes, 'lista_files': lista_files}
    return dizionario


@login_required()
def index(request, pk=None):
    """
    Radice del File System, inizio navigazione.
    """
    # Recupero la lista dei files e delle directory qui presenti.
    lista_inodes = INode.objects.filter(padre=pk).order_by('nome')
    lista_files = SiFile.objects.filter(inode=pk).order_by('nome')

    # Preparo il link per salire di un livello considerando il livello radice quello con padre None.
    if pk is None:
        su = reverse('fs:index')        # Genero il link per salire di un livello
        up = reverse('fs:upload')       # Genero il link per l'upload
    else:
        up = reverse('fs:upload', kwargs={'pk': pk})
        inode_appoggio = INode.objects.get(pk=pk)
        inode_su = inode_appoggio.padre
        if inode_su is None:
            su = reverse('fs:index')
        else:
            su = reverse('fs:index', kwargs={'pk': inode_su.pk})

    # Compongo il dizionario.
    context_dict = {'lista_inodes': lista_inodes, 'lista_files': lista_files, 'nodo': pk, 'su': su, 'up': up}

    # Visualizzo la risposta.
    return render(request, 'sifilesmanager/fs_index.html', context_dict)


@login_required
def fileupload(request, pk=None):
    """
    Carica un file nel sistema.
     Controlla se l'inode passato è valido altrimenti segnala errore
    print("pk = ", pk)
    inode = None
    if pk != 'None':
        try:
            inode = INode.objects.get(pk=pk)
        except INode.DoesNotExist:
            raise Http404("INode inesistente ! Cosa stai combinando ?")
    """

    # Verifico se l'inode esiste altrimenti segnalo errore.
    if pk is None:
        inode = None
    else:
        try:
            inode = INode.objects.get(pk=pk)
        except INode.DoesNotExist:
            raise Http404("INode inesistente ! Cosa stai combinando ?")

    if request.method == 'POST':
        form = SiFileForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = SiFile(filename=request.FILES['filename'], descrizione=request.POST['descrizione'], inode=inode)
            newdoc.save()
            return HttpResponse('<script type="text/javascript">window.opener.location.reload(false); \
                window.close();</script>')
        else:
            print(form.errors)
    else:
        form = SiFileForm()

    # Popola il dizionario per il template. Occhio che metto anche 'pk' altrimenti poi diventi scemo !
    context_dict = {'form': form, 'pk': pk}

    # Visualizza il template.
    return render(request, 'sifilesmanager/fs_upload.html', context_dict)


@login_required()
def file_delete(request, pk):
    """
    FILE : Elimina il file.
    """
    # Cerca di recuperare i dati del file e se non ci riesce segnala errore.
    try:
        sifile = SiFile.objects.get(pk=pk)
    except SiFile.DoesNotExist:
        raise Http404("File inesistente !")

    # Se è un POST vuol dire che ci sono già passato e che ho confermato la cancellazione, quindi eseguo.
    if request.method == 'POST':
        radice = settings.SIFILEDATA_ROOT
        filefisico = os.path.join(radice, sifile.pathurl, sifile.url)
        os.remove(filefisico)
        sifile.delete()
        return HttpResponse('<script type="text/javascript">window.opener.location.reload(false); \
                window.close();</script>')
    else:
        # Altrimenti visualizzo il form con la domanda se voglio cancellare.
        context_dict = {'sifile': sifile}
        return render(request, 'sifilesmanager/file_del.html', context_dict)
# endregion


# region FOLDERS
@login_required()
def folder_add(request, inodenumber):
    """
    FOLDER : Dato una cartella ne crea una all'interno.
    """
    # Cerca di recuperare l'inode e se non ci riesce segnala errore.
    inode = None
    if inodenumber != 'None':
        try:
            inode = INode.objects.get(pk=inodenumber)
        except INode.DoesNotExist:
            raise Http404("INode inesistente !")

    # Legge i dati dal POST e li analizza per salvarli
    if request.method == 'POST':
        form = INodeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.padre = inode
            post.save()
            return HttpResponse('<script type="text/javascript">window.opener.location.reload(false); \
                window.close();</script>')
        else:
            print(form.errors)
    else:
        form = INodeForm()

    # Popola il dizionario per il template.
    context_dict = {'form': form, 'inodenumber': inodenumber}

    # Visualizza il template.
    return render(request, 'sifilesmanager/folder_cu.html', context_dict)


@login_required()
def folder_edit(request, pk):
    """
    FOLDER : Modifica dei dati della cartella.
    """
    # Cerca di recuperare i dati del folder e se non ci riesce segnala errore.
    try:
        inode = INode.objects.get(pk=pk)
    except INode.DoesNotExist:
        raise Http404("INode inesistente !")

    # Legge i dati dal POST e li analizza per salvarli
    if request.method == 'POST':
        form = INodeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            inode.nome = post.nome
            inode.descrizione = post.descrizione
            inode.save()
            return HttpResponse('<script type="text/javascript">window.opener.location.reload(false); \
                window.close();</script>')
        else:
            print(form.errors)
    else:
        form = INodeForm(instance=inode)

    # Popola il dizionario per il template.
    context_dict = {'form': form, 'pk': pk}

    # Visualizza il template.
    return render(request, 'sifilesmanager/folder_cu.html', context_dict)


@login_required()
def folder_delete(request, pk):
    """
    FOLDER : Elimina la cartella se è vuota.
    """
    # Cerca di recuperare i dati del folder e se non ci riesce segnala errore.
    try:
        inode = INode.objects.get(pk=pk)
    except INode.DoesNotExist:
        raise Http404("INode inesistente !")

    # Ora controllo se il folder ne contiene altri.
    if inode.inode_set.count() > 0:
        return HttpResponse('<script type="text/javascript">alert("La cartella non può essere cancellata perchè non è vuota !"); \
            window.close();</script>')

    # Se è un POST vuol dire che ci sono già passato e che ho confermato la cancellazione, quindi eseguo.
    if request.method == 'POST':
        # padre = inode.padre
        inode.delete()
        return HttpResponse('<script type="text/javascript">window.opener.location.reload(false); \
                window.close();</script>')
    else:
        # Altrimenti visualizzo il form con la domanda se voglio cancellare.
        context_dict = {'folder': inode}
        return render(request, 'sifilesmanager/folder_del.html', context_dict)
# endregion

templates/sifilesmanager/file_del.html
{% extends "base_popup.html" %}

{% block title %}Cancellazione File{% endblock %}

{% block header %}Cancellazione File{% endblock %}

{% block body_block %}

   <form method="post" class="form">
        {% csrf_token %}
        <strong>{{ sifile.nome }}</strong>
        <br/><br/>
        ATTENZIONE - Questo File verrà eliminato !
        <br/><br>

        <input class="btn btn-default" type="button" onclick="window.close()" value="Annulla">
        <input class="btn btn-danger" type="submit" value="Conferma" />
    </form>
{% endblock %}

templates/sifilesmanager/folder_cu.html
{% extends 'base_popup.html' %}

{% load staticfiles %}

{% block title %}Cartella {% endblock %}
{% block header %}Cartella {% endblock %}

{% block body_block %}

<form action="" method="post" class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-default" type="submit" value="Salva" />
    <input class="btn btn-danger" type="button" onclick="window.close()" value="Annulla">
</form>

{% endblock %}

templates/sifilesmanager/folder_del.html
{% extends "base_popup.html" %}

{% block title %}Cancellazione Cartella{% endblock %}

{% block header %}Cancellazione Cartella{% endblock %}

{% block body_block %}

   <form method="post" class="form">
        {% csrf_token %}
        <strong>{{ folder.nome }}</strong>
        <br/><br/>
        ATTENZIONE - Questa Cartella verrà eliminata !
        <br/><br>

        <input class="btn btn-default" type="button" onclick="window.close()" value="Annulla">
        <input class="btn btn-danger" type="submit" value="Conferma" />
    </form>
{% endblock %}

templates/sifilesmanager/fs_index.html
{% extends 'base-jqxrenamed.html' %}

{% load staticfiles %}

{% block title %}File System{% endblock %}
{% block header %}File System{% endblock %}

{% block body_block %}

        {% comment %}
            Mettere qui la parte relativa alle scorciatoie per il cammino
        {% endcomment %}


    {% if lista_inodes %}
        <div class="row col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Cartella</th>
                        <th>Descrizione</th>
                        <th>Timestamp</th>
                        <th>Azione</th>
                    </tr>
                </thead>

                <tbody>
                {% for inode in lista_inodes %}
                    <tr>
                        <td><li><a class="sphinxsidebar" href="{% url 'fs:index' inode.pk %}">{{ inode.nome }}</a></li></td>
                        <td>{{ inode.descrizione }}</td>
                        <td>{{ inode.size|filesizeformat }}</td>
                        <td><h5><small>
                            Creato : {{ inode.data_creazione }}<br>
                            Modificato : {{ inode.data_aggiornamento }}
                        </small></h5></td>
                        <td>
                            <a class="glyphicon glyphicon-remove" href="{% url 'fs:folder_delete' inode.pk %}" onclick="return showAddAnotherPopup(this);"></a>
                            <a class="glyphicon glyphicon-edit" href="{% url 'fs:folder_edit' inode.pk %}" onclick="return showAddAnotherPopup(this);"></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="row col-md-8">
            Nessuna Cartella Presente !
        </div>
    {% endif %}


    {% if lista_files %}
        <div class="row col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Descrizione</th>
                        <th>Size</th>
                        <th>Timestamp</th>
                        <th>Azione</th>
                    </tr>
                </thead>

                <tbody>
                {% for file in lista_files %}
                    <tr>
                        <td><li><a href="/data/{{file.pathurl}}/{{file.url}}" download="{{file.nome}}">{{ file.nome }}</a></li></td>
                        <td>{{ file.descrizione }}</td>
                        <td>{{ file.size|filesizeformat }}</td>
                        <td><h5><small>
                            Creato : {{ file.data_creazione }}<br>
                            Modificato : {{ file.data_aggiornamento }}
                        </small></h5></td>
                        <td>
                            <a class="glyphicon glyphicon-remove" href="{% url 'fs:file_delete' file.pk %}" onclick="return showAddAnotherPopup(this);"></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="row col-md-8">
            Nessun File Presente !
        </div>
    {% endif %}

    <br>

    <div class="row col-md-12" align="center">
        <a class="btn btn-default" href="{{ su }}" role="button">Su di un livello</a>
        <a class="btn btn-default" href="{{ up }}" onclick="return showAddAnotherPopup(this);" role="button">Upload File</a>
        <a class="btn btn-default" href="{% url 'fs:folder_add' nodo %}" onclick="return showAddAnotherPopup(this);" role="button">Crea Cartella</a>
    </div>

{% endblock %}

templates/sifilesmanager/fs_upload.html
{% extends 'base_popup.html' %}

{% load staticfiles %}

{% block title %}File Upload {% endblock %}
{% block header %}File Upload {% endblock %}

{% block body_block %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-default" type="submit" value="Salva" />
    <input class="btn btn-danger" type="button" onclick="window.close()" value="Annulla">
</form>

{% endblock %}